import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { getPeoples } from "@/lib/queries/peopleQuery";

export default function Home({ peoples }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <h1>Peoples Tables</h1>
          <ul>
            {peoples.map((people) => (
              <li key={people.id}>
                {people.name}, {people.birth}
              </li>
            ))}
          </ul>
        </div>
      </main>
    </>
  );
}

export async function getServerSideProps() {
  try {
    const peoples = await getPeoples();
    return { props: { peoples } };
  } catch (error) {
    console.error("Error fetching users:", error);
    return { props: { peoples: [] } };
  }
}
